// ignore_for_file: camel_case_types, non_constant_identifier_names, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for IAMF_decoder.h.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class EclipsaIamfDecoderBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  EclipsaIamfDecoderBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  EclipsaIamfDecoderBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// @brief     Open an iamf decoder.
  /// @return    return an iamf decoder handle.
  IAMF_DecoderHandle IAMF_decoder_open() {
    return _IAMF_decoder_open();
  }

  late final _IAMF_decoder_openPtr =
      _lookup<ffi.NativeFunction<IAMF_DecoderHandle Function()>>(
        'IAMF_decoder_open',
      );
  late final _IAMF_decoder_open =
      _IAMF_decoder_openPtr.asFunction<IAMF_DecoderHandle Function()>();

  /// @brief     Close an iamf decoder.
  /// @param     [in] handle : iamf decoder handle.
  int IAMF_decoder_close(IAMF_DecoderHandle handle) {
    return _IAMF_decoder_close(handle);
  }

  late final _IAMF_decoder_closePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(IAMF_DecoderHandle)>>(
        'IAMF_decoder_close',
      );
  late final _IAMF_decoder_close =
      _IAMF_decoder_closePtr.asFunction<int Function(IAMF_DecoderHandle)>();

  /// @brief     Set the IAMF profile for the decoder.
  ///
  /// This function sets the IAMF profile that the decoder will use for processing
  /// audio data. The profile determines the features and capabilities that the
  /// decoder will support. The profile must be set before configuring the decoder
  /// with descriptor OBUs.
  ///
  /// @param     [in] handle : IAMF decoder handle.
  /// @param     [in] profile : The IAMF profile to set. Must be one of the values
  /// defined in @ref IA_Profile.
  /// @return    @ref IAErrCode. IAMF_OK on success, IAMF_ERR_BAD_ARG on invalid
  /// parameters.
  ///
  /// @note      The profile must be set before calling @ref IAMF_decoder_configure
  /// with descriptor OBUs. Setting the profile after configuration may not have
  /// the desired effect.
  int IAMF_decoder_set_profile(IAMF_DecoderHandle handle, IA_Profile profile) {
    return _IAMF_decoder_set_profile(handle, profile.value);
  }

  late final _IAMF_decoder_set_profilePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(IAMF_DecoderHandle, ffi.Int)>
      >('IAMF_decoder_set_profile');
  late final _IAMF_decoder_set_profile =
      _IAMF_decoder_set_profilePtr.asFunction<
        int Function(IAMF_DecoderHandle, int)
      >();

  /// @brief     Get the current IAMF profile of the decoder.
  ///
  /// This function retrieves the currently set IAMF profile of the decoder. The
  /// profile determines the features and capabilities that the decoder supports.
  ///
  /// @param     [in] handle : IAMF decoder handle.
  /// @return    The current IAMF profile, or ck_iamf_profile_none if the handle
  /// is invalid.
  ///
  /// @note      The returned profile may be different from the one set by
  /// @ref IAMF_decoder_set_profile if the decoder has been configured
  /// with an IA Sequence Header OBU that specifies a different profile.
  IA_Profile IAMF_decoder_get_profile(IAMF_DecoderHandle handle) {
    return IA_Profile.fromValue(_IAMF_decoder_get_profile(handle));
  }

  late final _IAMF_decoder_get_profilePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(IAMF_DecoderHandle)>>(
        'IAMF_decoder_get_profile',
      );
  late final _IAMF_decoder_get_profile =
      _IAMF_decoder_get_profilePtr.asFunction<
        int Function(IAMF_DecoderHandle)
      >();

  /// @brief     Configurate an iamf decoder. The first configurating decoder must
  /// need descriptor OBUs, then if only some properties have been
  /// changed, @ref IAMF_decoder_set_mix_presentation_label API. the
  /// descriptor OBUs is not needed.
  /// @param     [in] handle : iamf decoder handle.
  /// @param     [in] data : the bitstream.
  /// @param     [in] size : the size in bytes of bitstream.
  /// @param     [in & out] rsize : the size in bytes of bitstream that has been
  /// consumed. If is null, it means the data is the
  /// complete configuration OBUs.
  /// @return    @ref IAErrCode.
  int IAMF_decoder_configure(
    IAMF_DecoderHandle handle,
    ffi.Pointer<ffi.Uint8> data,
    int size,
    ffi.Pointer<ffi.Uint32> rsize,
  ) {
    return _IAMF_decoder_configure(handle, data, size, rsize);
  }

  late final _IAMF_decoder_configurePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            IAMF_DecoderHandle,
            ffi.Pointer<ffi.Uint8>,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('IAMF_decoder_configure');
  late final _IAMF_decoder_configure =
      _IAMF_decoder_configurePtr.asFunction<
        int Function(
          IAMF_DecoderHandle,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint32>,
        )
      >();

  /// @brief     Decode bitstream.
  /// @param     [in] handle : iamf decoder handle.
  /// @param     [in] data : the OBUs in bitstream.
  /// if is null, the output is delay signal.
  /// @param     [in] size : the size in bytes of bitstream.
  /// @param     [in & out] rsize : the size in bytes of bitstream that has been
  /// consumed. If it is null, it means the data is
  /// a complete access unit which includes all OBUs
  /// of substream frames and parameters.
  /// @param     [out] pcm : output signal.
  /// @return    the number of decoded samples or @ref IAErrCode.
  int IAMF_decoder_decode(
    IAMF_DecoderHandle handle,
    ffi.Pointer<ffi.Uint8> data,
    int size,
    ffi.Pointer<ffi.Uint32> rsize,
    ffi.Pointer<ffi.Void> pcm,
  ) {
    return _IAMF_decoder_decode(handle, data, size, rsize, pcm);
  }

  late final _IAMF_decoder_decodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            IAMF_DecoderHandle,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Pointer<ffi.Uint32>,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('IAMF_decoder_decode');
  late final _IAMF_decoder_decode =
      _IAMF_decoder_decodePtr.asFunction<
        int Function(
          IAMF_DecoderHandle,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint32>,
          ffi.Pointer<ffi.Void>,
        )
      >();

  /// @brief     Set mix presentation id to select the mix that match the user's
  /// preferences.
  /// @param     [in] handle : iamf decoder handle.
  /// @param     [in] id : an identifier for a Mix Presentation.
  /// @return    @ref IAErrCode.
  int IAMF_decoder_set_mix_presentation_id(IAMF_DecoderHandle handle, int id) {
    return _IAMF_decoder_set_mix_presentation_id(handle, id);
  }

  late final _IAMF_decoder_set_mix_presentation_idPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(IAMF_DecoderHandle, ffi.Uint64)>
      >('IAMF_decoder_set_mix_presentation_id');
  late final _IAMF_decoder_set_mix_presentation_id =
      _IAMF_decoder_set_mix_presentation_idPtr.asFunction<
        int Function(IAMF_DecoderHandle, int)
      >();

  /// @brief     Get selected mix presentation id.
  /// @param     [in] handle : iamf decoder handle.
  /// @return    valid id ( >= 0) or -1.
  int IAMF_decoder_get_mix_presentation_id(IAMF_DecoderHandle handle) {
    return _IAMF_decoder_get_mix_presentation_id(handle);
  }

  late final _IAMF_decoder_get_mix_presentation_idPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(IAMF_DecoderHandle)>>(
        'IAMF_decoder_get_mix_presentation_id',
      );
  late final _IAMF_decoder_get_mix_presentation_id =
      _IAMF_decoder_get_mix_presentation_idPtr.asFunction<
        int Function(IAMF_DecoderHandle)
      >();

  /// @brief     Set sound system output layout.
  /// @param     [in] handle : iamf decoder handle.
  /// @param     [in] ss : the sound system (@ref IAMF_SoundSystem).
  /// @return    @ref IAErrCode.
  int IAMF_decoder_output_layout_set_sound_system(
    IAMF_DecoderHandle handle,
    IAMF_SoundSystem ss,
  ) {
    return _IAMF_decoder_output_layout_set_sound_system(handle, ss.value);
  }

  late final _IAMF_decoder_output_layout_set_sound_systemPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(IAMF_DecoderHandle, ffi.Int)>
      >('IAMF_decoder_output_layout_set_sound_system');
  late final _IAMF_decoder_output_layout_set_sound_system =
      _IAMF_decoder_output_layout_set_sound_systemPtr.asFunction<
        int Function(IAMF_DecoderHandle, int)
      >();

  /// @brief     Set binaural output layout.
  /// @param     [in] handle : iamf decoder handle.
  /// @return    @ref IAErrCode.
  int IAMF_decoder_output_layout_set_binaural(IAMF_DecoderHandle handle) {
    return _IAMF_decoder_output_layout_set_binaural(handle);
  }

  late final _IAMF_decoder_output_layout_set_binauralPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(IAMF_DecoderHandle)>>(
        'IAMF_decoder_output_layout_set_binaural',
      );
  late final _IAMF_decoder_output_layout_set_binaural =
      _IAMF_decoder_output_layout_set_binauralPtr.asFunction<
        int Function(IAMF_DecoderHandle)
      >();

  /// @brief     Get the number of channels of the sound system.
  /// @param     [in] ss : the sound system (@ref IAMF_SoundSystem).
  /// @return    the number of channels.
  int IAMF_layout_sound_system_channels_count(IAMF_SoundSystem ss) {
    return _IAMF_layout_sound_system_channels_count(ss.value);
  }

  late final _IAMF_layout_sound_system_channels_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
        'IAMF_layout_sound_system_channels_count',
      );
  late final _IAMF_layout_sound_system_channels_count =
      _IAMF_layout_sound_system_channels_countPtr.asFunction<
        int Function(int)
      >();

  /// @brief     Get the number of channels of binaural pattern.
  /// @return    the number of channels.
  int IAMF_layout_binaural_channels_count() {
    return _IAMF_layout_binaural_channels_count();
  }

  late final _IAMF_layout_binaural_channels_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
        'IAMF_layout_binaural_channels_count',
      );
  late final _IAMF_layout_binaural_channels_count =
      _IAMF_layout_binaural_channels_countPtr.asFunction<int Function()>();

  /// @brief     Get the codec capability of iamf. Need to free string manually.
  /// The codec string format will be:
  /// "iamf.xxx.yyy.Opus;iamf.xxx.yyy.mp4a.40.2" Where xxx is three
  /// digits to indicate the value of the primary_profile and yyy
  /// is three digits to indicate the value of the additional_profile.
  /// @return    the supported codec string.
  ffi.Pointer<ffi.Char> IAMF_decoder_get_codec_capability() {
    return _IAMF_decoder_get_codec_capability();
  }

  late final _IAMF_decoder_get_codec_capabilityPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'IAMF_decoder_get_codec_capability',
      );
  late final _IAMF_decoder_get_codec_capability =
      _IAMF_decoder_get_codec_capabilityPtr.asFunction<
        ffi.Pointer<ffi.Char> Function()
      >();

  /// @brief Set loudness normalization target for IAMF decoder
  ///
  /// This function configures the target loudness for loudness normalization
  /// according to EBU R128 standard. Normalization ensures consistent loudness
  /// across different audio sources.
  ///
  /// @param     [in] handle : IAMF decoder handle
  /// @param     [in] loudness : Target loudness in dB (LKFS):
  /// - loudness = 0.0f: DISABLE loudness normalization (use original loudness)
  /// - loudness < 0: Enable normalization to target loudness
  /// * Common values: -23.0 (EBU R128), -24.0 (ATSC A/85)
  /// * Example: -16.0 (YouTube), -14.0 (Spotify)
  /// - loudness > 0: INVALID (returns IAMF_ERR_BAD_ARG)
  ///
  /// @return    @ref IAErrCode. IAMF_OK on success, error code on failure.
  ///
  /// @note IMPORTANT: loudness = 0.0f is a SPECIAL FLAG to disable normalization.
  /// It does NOT mean normalize to 0 dB (which would be digital full scale).
  /// To disable normalization, explicitly set loudness = 0.0f.
  ///
  /// @note Normalization is only applied if the presentation is active.
  ///
  /// @see EBU R128 Technical Recommendation EBU - TECH 3344
  int IAMF_decoder_set_normalization_loudness(
    IAMF_DecoderHandle handle,
    double loudness,
  ) {
    return _IAMF_decoder_set_normalization_loudness(handle, loudness);
  }

  late final _IAMF_decoder_set_normalization_loudnessPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(IAMF_DecoderHandle, ffi.Float)>
      >('IAMF_decoder_set_normalization_loudness');
  late final _IAMF_decoder_set_normalization_loudness =
      _IAMF_decoder_set_normalization_loudnessPtr.asFunction<
        int Function(IAMF_DecoderHandle, double)
      >();

  /// @brief     Set pcm output bitdepth.
  /// @param     [in] handle : iamf decoder handle.
  /// @param     [in] bit_depth : target bit depth in bit. Must be one of the
  /// values defined in @ref IAMF_SampleBitDepth
  /// (16, 24, or 32 bits).
  /// @return    @ref IAErrCode.
  int IAMF_decoder_set_bit_depth(IAMF_DecoderHandle handle, int bit_depth) {
    return _IAMF_decoder_set_bit_depth(handle, bit_depth);
  }

  late final _IAMF_decoder_set_bit_depthPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(IAMF_DecoderHandle, ffi.Uint32)>
      >('IAMF_decoder_set_bit_depth');
  late final _IAMF_decoder_set_bit_depth =
      _IAMF_decoder_set_bit_depthPtr.asFunction<
        int Function(IAMF_DecoderHandle, int)
      >();

  /// @brief     Enable peak limiter. In the decoder, the peak limiter is enabled
  /// by default.
  /// @param     [in] handle : iamf decoder handle.
  /// @param     [in] enable : 1 indicates enabled, and 0 indicates disable.
  /// @return    @ref IAErrCode.
  int IAMF_decoder_peak_limiter_enable(IAMF_DecoderHandle handle, int enable) {
    return _IAMF_decoder_peak_limiter_enable(handle, enable);
  }

  late final _IAMF_decoder_peak_limiter_enablePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(IAMF_DecoderHandle, ffi.Uint32)>
      >('IAMF_decoder_peak_limiter_enable');
  late final _IAMF_decoder_peak_limiter_enable =
      _IAMF_decoder_peak_limiter_enablePtr.asFunction<
        int Function(IAMF_DecoderHandle, int)
      >();

  /// @brief     Set peak threshold value of peak limiter.
  ///
  /// The peak limiter is enabled by default with a threshold of -1.0 dBFS. Use
  /// this function to override the default threshold value.
  ///
  /// @param     [in] handle : iamf decoder handle.
  /// @param     [in] db : peak threshold in dB.
  /// @return    @ref IAErrCode.
  int IAMF_decoder_peak_limiter_set_threshold(
    IAMF_DecoderHandle handle,
    double db,
  ) {
    return _IAMF_decoder_peak_limiter_set_threshold(handle, db);
  }

  late final _IAMF_decoder_peak_limiter_set_thresholdPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(IAMF_DecoderHandle, ffi.Float)>
      >('IAMF_decoder_peak_limiter_set_threshold');
  late final _IAMF_decoder_peak_limiter_set_threshold =
      _IAMF_decoder_peak_limiter_set_thresholdPtr.asFunction<
        int Function(IAMF_DecoderHandle, double)
      >();

  /// @brief     Get peak threshold value of peak limiter.
  /// @param     [in] handle : iamf decoder handle.
  /// @return    Peak threshold in dB.
  double IAMF_decoder_peak_limiter_get_threshold(IAMF_DecoderHandle handle) {
    return _IAMF_decoder_peak_limiter_get_threshold(handle);
  }

  late final _IAMF_decoder_peak_limiter_get_thresholdPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(IAMF_DecoderHandle)>>(
        'IAMF_decoder_peak_limiter_get_threshold',
      );
  late final _IAMF_decoder_peak_limiter_get_threshold =
      _IAMF_decoder_peak_limiter_get_thresholdPtr.asFunction<
        double Function(IAMF_DecoderHandle)
      >();

  /// @brief     Set pcm output sampling rate.
  /// @param     [in] handle : iamf decoder handle.
  /// @param     [in] rate : sampling rate. Must be one of the values defined in
  /// @ref IAMF_SamplingRate (7350, 8000, 11025, 16000,
  /// 22050, 24000, 32000, 44100, 48000, 64000, 88200,
  /// 96000, 176400, or 192000 Hz).
  /// @return    @ref IAErrCode.
  int IAMF_decoder_set_sampling_rate(IAMF_DecoderHandle handle, int rate) {
    return _IAMF_decoder_set_sampling_rate(handle, rate);
  }

  late final _IAMF_decoder_set_sampling_ratePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(IAMF_DecoderHandle, ffi.Uint32)>
      >('IAMF_decoder_set_sampling_rate');
  late final _IAMF_decoder_set_sampling_rate =
      _IAMF_decoder_set_sampling_ratePtr.asFunction<
        int Function(IAMF_DecoderHandle, int)
      >();

  /// @brief     Set gain offset for a specific audio element.
  /// @param     [in] handle : iamf decoder handle.
  /// @param     [in] id : audio element identifier.
  /// @param     [in] gain : gain offset value in dB.
  /// @return    @ref IAErrCode.
  int IAMF_decoder_set_audio_element_gain_offset(
    IAMF_DecoderHandle handle,
    int id,
    double gain,
  ) {
    return _IAMF_decoder_set_audio_element_gain_offset(handle, id, gain);
  }

  late final _IAMF_decoder_set_audio_element_gain_offsetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(IAMF_DecoderHandle, ffi.Uint32, ffi.Float)
        >
      >('IAMF_decoder_set_audio_element_gain_offset');
  late final _IAMF_decoder_set_audio_element_gain_offset =
      _IAMF_decoder_set_audio_element_gain_offsetPtr.asFunction<
        int Function(IAMF_DecoderHandle, int, double)
      >();

  /// @brief     Get gain offset for a specific audio element.
  /// @param     [in] handle : iamf decoder handle.
  /// @param     [in] id : audio element identifier.
  /// @param     [out] gain : pointer to store the gain offset value in dB.
  /// @return    @ref IAErrCode.
  int IAMF_decoder_get_audio_element_gain_offset(
    IAMF_DecoderHandle handle,
    int id,
    ffi.Pointer<ffi.Float> gain,
  ) {
    return _IAMF_decoder_get_audio_element_gain_offset(handle, id, gain);
  }

  late final _IAMF_decoder_get_audio_element_gain_offsetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            IAMF_DecoderHandle,
            ffi.Uint32,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('IAMF_decoder_get_audio_element_gain_offset');
  late final _IAMF_decoder_get_audio_element_gain_offset =
      _IAMF_decoder_get_audio_element_gain_offsetPtr.asFunction<
        int Function(IAMF_DecoderHandle, int, ffi.Pointer<ffi.Float>)
      >();

  /// @brief     Enable or disable head tracking for 3D audio rendering.
  ///
  /// This function enables or disables head tracking functionality. When enabled,
  /// the decoder will use head rotation data to create immersive 3D audio
  /// experiences. Head tracking must be enabled before setting head rotation
  /// values.
  ///
  /// @param     [in] handle : IAMF decoder handle.
  /// @param     [in] enable : 1 to enable head tracking, 0 to disable.
  /// @return    @ref IAErrCode.
  int IAMF_decoder_enable_head_tracking(IAMF_DecoderHandle handle, int enable) {
    return _IAMF_decoder_enable_head_tracking(handle, enable);
  }

  late final _IAMF_decoder_enable_head_trackingPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(IAMF_DecoderHandle, ffi.Uint32)>
      >('IAMF_decoder_enable_head_tracking');
  late final _IAMF_decoder_enable_head_tracking =
      _IAMF_decoder_enable_head_trackingPtr.asFunction<
        int Function(IAMF_DecoderHandle, int)
      >();

  /// @brief     Set the head rotation for 3D audio rendering in world space.
  ///
  /// This function sets the head rotation using quaternion representation to
  /// counter-rotate the intermediate Ambisonic bed, producing stable sound sources
  /// in binaural reproduction. The head rotation is essential for immersive 3D
  /// audio experiences where the listener's head orientation affects audio
  /// perception.
  ///
  /// The function uses a right-handed coordinate system with the following
  /// reference frame:
  /// - X axis: points to the right
  /// - Y axis: points up
  /// - Z axis: points backward (swap sign of z if using front-facing Z coordinate)
  ///
  /// The quaternion will be automatically normalized if not unit length. Invalid
  /// quaternions (too close to zero) will be rejected.
  ///
  /// @param     [in] handle : IAMF decoder handle.
  /// @param     [in] w : Quaternion scalar component (W).
  /// @param     [in] x : Quaternion X component.
  /// @param     [in] y : Quaternion Y component.
  /// @param     [in] z : Quaternion Z component.
  /// @return    @ref IAErrCode. IAMF_OK on success, IAMF_ERR_BAD_ARG on invalid
  /// parameters.
  ///
  /// @note      This function should be called regularly during audio playback to
  /// update the head position based on sensor data from head tracking devices. The
  /// head rotation data is used during the rendering process to create realistic
  /// 3D audio spatialization in world space.
  ///
  /// @warning   Head rotation functionality is only effective for binaural output
  /// layout. The decoder must be configured for binaural output using
  /// @ref IAMF_decoder_output_layout_set_binaural() before calling this
  /// function. For other output layouts (stereo, multichannel), head rotation
  /// settings will be stored but will not affect the audio output.
  int IAMF_decoder_set_head_rotation(
    IAMF_DecoderHandle handle,
    double w,
    double x,
    double y,
    double z,
  ) {
    return _IAMF_decoder_set_head_rotation(handle, w, x, y, z);
  }

  late final _IAMF_decoder_set_head_rotationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            IAMF_DecoderHandle,
            ffi.Float,
            ffi.Float,
            ffi.Float,
            ffi.Float,
          )
        >
      >('IAMF_decoder_set_head_rotation');
  late final _IAMF_decoder_set_head_rotation =
      _IAMF_decoder_set_head_rotationPtr.asFunction<
        int Function(IAMF_DecoderHandle, double, double, double, double)
      >();

  /// @brief     Get comprehensive IAMF stream information.
  ///
  /// This function retrieves detailed information about the configured IAMF
  /// stream, including codec parameters, audio format specifications, and
  /// available mix presentations. The stream information is essential for
  /// applications to understand the capabilities and configuration of the audio
  /// stream for proper playback setup.
  ///
  /// The function must be called after successful decoder configuration using
  /// @ref IAMF_decoder_configure. It returns a pointer to an @ref IAMF_StreamInfo
  /// structure containing:
  /// - Maximum frame size for buffer allocation
  /// - IAMF profile information (primary and additional)
  /// - Codec types and parameters (Opus, AAC, FLAC, etc.)
  /// - Sampling rate and frame size information
  /// - Available mix presentations with their audio elements
  /// - Audio element rendering modes and gain settings
  ///
  /// @param     [in] handle : IAMF decoder handle. Must be a valid handle returned
  /// by
  /// @ref IAMF_decoder_open and successfully configured.
  ///
  /// @return    Pointer to allocated @ref IAMF_StreamInfo structure containing
  /// stream information, or NULL if the decoder is not configured or an error
  /// occurs.
  ///
  /// @note      The returned structure and all its nested arrays are dynamically
  /// allocated. After using the stream information, the caller MUST free the
  /// allocated memory by calling @ref IAMF_decoder_free_stream_info to prevent
  /// memory leaks. The stream information remains valid until the decoder is
  /// reconfigured or closed.
  ///
  /// @warning   Do not attempt to free the returned structure manually using
  /// standard free() as it contains nested allocations that require proper
  /// cleanup. Always use @ref IAMF_decoder_free_stream_info for proper resource
  /// management.
  ffi.Pointer<IAMF_StreamInfo> IAMF_decoder_get_stream_info(
    IAMF_DecoderHandle handle,
  ) {
    return _IAMF_decoder_get_stream_info(handle);
  }

  late final _IAMF_decoder_get_stream_infoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<IAMF_StreamInfo> Function(IAMF_DecoderHandle)
        >
      >('IAMF_decoder_get_stream_info');
  late final _IAMF_decoder_get_stream_info =
      _IAMF_decoder_get_stream_infoPtr.asFunction<
        ffi.Pointer<IAMF_StreamInfo> Function(IAMF_DecoderHandle)
      >();

  /// @brief     Free the memory allocated for stream info.
  /// @param     [in] info : pointer to the stream info structure to be freed.
  void IAMF_decoder_free_stream_info(ffi.Pointer<iamf_stream_info_t> info) {
    return _IAMF_decoder_free_stream_info(info);
  }

  late final _IAMF_decoder_free_stream_infoPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<iamf_stream_info_t>)>
      >('IAMF_decoder_free_stream_info');
  late final _IAMF_decoder_free_stream_info =
      _IAMF_decoder_free_stream_infoPtr.asFunction<
        void Function(ffi.Pointer<iamf_stream_info_t>)
      >();
}

enum IA_Profile {
  IA_PROFILE_NONE(-1),
  IA_PROFILE_SIMPLE(0),
  IA_PROFILE_BASE(1),
  IA_PROFILE_BASE_ENHANCED(2),
  IA_PROFILE_BASE_ADVANCED(3),
  IA_PROFILE_ADVANCED_1(4),
  IA_PROFILE_ADVANCED_2(5);

  final int value;
  const IA_Profile(this.value);

  static IA_Profile fromValue(int value) => switch (value) {
    -1 => IA_PROFILE_NONE,
    0 => IA_PROFILE_SIMPLE,
    1 => IA_PROFILE_BASE,
    2 => IA_PROFILE_BASE_ENHANCED,
    3 => IA_PROFILE_BASE_ADVANCED,
    4 => IA_PROFILE_ADVANCED_1,
    5 => IA_PROFILE_ADVANCED_2,
    _ => throw ArgumentError('Unknown value for IA_Profile: $value'),
  };
}

/// Audio Element Type
enum IAMF_AudioElementType {
  AUDIO_ELEMENT_INVALID(-1),
  AUDIO_ELEMENT_CHANNEL_BASED(0),
  AUDIO_ELEMENT_SCENE_BASED(1),
  AUDIO_ELEMENT_OBJECT_BASED(2),
  AUDIO_ELEMENT_COUNT(3);

  final int value;
  const IAMF_AudioElementType(this.value);

  static IAMF_AudioElementType fromValue(int value) => switch (value) {
    -1 => AUDIO_ELEMENT_INVALID,
    0 => AUDIO_ELEMENT_CHANNEL_BASED,
    1 => AUDIO_ELEMENT_SCENE_BASED,
    2 => AUDIO_ELEMENT_OBJECT_BASED,
    3 => AUDIO_ELEMENT_COUNT,
    _ => throw ArgumentError('Unknown value for IAMF_AudioElementType: $value'),
  };
}

enum IAMF_LayoutType {
  IAMF_LAYOUT_TYPE_NOT_DEFINED(0),
  IAMF_LAYOUT_TYPE_LOUDSPEAKERS_SS_CONVENTION(2),
  IAMF_LAYOUT_TYPE_BINAURAL(3);

  final int value;
  const IAMF_LayoutType(this.value);

  static IAMF_LayoutType fromValue(int value) => switch (value) {
    0 => IAMF_LAYOUT_TYPE_NOT_DEFINED,
    2 => IAMF_LAYOUT_TYPE_LOUDSPEAKERS_SS_CONVENTION,
    3 => IAMF_LAYOUT_TYPE_BINAURAL,
    _ => throw ArgumentError('Unknown value for IAMF_LayoutType: $value'),
  };
}

enum IAMF_SoundSystem {
  SOUND_SYSTEM_INVALID(-1),

  /// 0+2+0, 0
  SOUND_SYSTEM_A(0),

  /// 0+5+0, 1
  SOUND_SYSTEM_B(1),

  /// 2+5+0, 1
  SOUND_SYSTEM_C(2),

  /// 4+5+0, 1
  SOUND_SYSTEM_D(3),

  /// 4+5+1, 1
  SOUND_SYSTEM_E(4),

  /// 3+7+0, 2
  SOUND_SYSTEM_F(5),

  /// 4+9+0, 1
  SOUND_SYSTEM_G(6),

  /// 9+10+3, 2
  SOUND_SYSTEM_H(7),

  /// 0+7+0, 1
  SOUND_SYSTEM_I(8),

  /// 4+7+0, 1
  SOUND_SYSTEM_J(9),

  /// 2+7+0, 1
  SOUND_SYSTEM_EXT_712(10),

  /// 2+3+0, 1
  SOUND_SYSTEM_EXT_312(11),

  /// 0+1+0, 0
  SOUND_SYSTEM_MONO(12),

  /// 6+9+0, 1
  SOUND_SYSTEM_EXT_916(13),

  /// 5+7+4, 1
  SOUND_SYSTEM_EXT_7154(14),
  SOUND_SYSTEM_END(15);

  static const SOUND_SYSTEM_NONE = SOUND_SYSTEM_INVALID;

  final int value;
  const IAMF_SoundSystem(this.value);

  static IAMF_SoundSystem fromValue(int value) => switch (value) {
    -1 => SOUND_SYSTEM_INVALID,
    0 => SOUND_SYSTEM_A,
    1 => SOUND_SYSTEM_B,
    2 => SOUND_SYSTEM_C,
    3 => SOUND_SYSTEM_D,
    4 => SOUND_SYSTEM_E,
    5 => SOUND_SYSTEM_F,
    6 => SOUND_SYSTEM_G,
    7 => SOUND_SYSTEM_H,
    8 => SOUND_SYSTEM_I,
    9 => SOUND_SYSTEM_J,
    10 => SOUND_SYSTEM_EXT_712,
    11 => SOUND_SYSTEM_EXT_312,
    12 => SOUND_SYSTEM_MONO,
    13 => SOUND_SYSTEM_EXT_916,
    14 => SOUND_SYSTEM_EXT_7154,
    15 => SOUND_SYSTEM_END,
    _ => throw ArgumentError('Unknown value for IAMF_SoundSystem: $value'),
  };

  @override
  String toString() {
    if (this == SOUND_SYSTEM_INVALID)
      return "IAMF_SoundSystem.SOUND_SYSTEM_INVALID, IAMF_SoundSystem.SOUND_SYSTEM_NONE";
    return super.toString();
  }
}

/// Codec ID
enum IAMF_CodecID {
  IAMF_CODEC_UNKNOWN(0),
  IAMF_CODEC_OPUS(1),
  IAMF_CODEC_AAC(2),
  IAMF_CODEC_FLAC(3),
  IAMF_CODEC_PCM(4),
  IAMF_CODEC_COUNT(5);

  /// no codec
  static const IAMF_CODEC_NONE = IAMF_CODEC_UNKNOWN;

  final int value;
  const IAMF_CodecID(this.value);

  static IAMF_CodecID fromValue(int value) => switch (value) {
    0 => IAMF_CODEC_UNKNOWN,
    1 => IAMF_CODEC_OPUS,
    2 => IAMF_CODEC_AAC,
    3 => IAMF_CODEC_FLAC,
    4 => IAMF_CODEC_PCM,
    5 => IAMF_CODEC_COUNT,
    _ => throw ArgumentError('Unknown value for IAMF_CodecID: $value'),
  };

  @override
  String toString() {
    if (this == IAMF_CODEC_UNKNOWN)
      return "IAMF_CodecID.IAMF_CODEC_UNKNOWN, IAMF_CodecID.IAMF_CODEC_NONE";
    return super.toString();
  }
}

/// IA channel layout type.
enum IAMF_LoudspeakerLayoutType {
  IA_CHANNEL_LAYOUT_INVALID(-1),

  /// 1.0.0
  IA_CHANNEL_LAYOUT_MONO(0),

  /// 2.0.0
  IA_CHANNEL_LAYOUT_STEREO(1),

  /// 5.1.0
  IA_CHANNEL_LAYOUT_510(2),

  /// 5.1.2
  IA_CHANNEL_LAYOUT_512(3),

  /// 5.1.4
  IA_CHANNEL_LAYOUT_514(4),

  /// 7.1.0
  IA_CHANNEL_LAYOUT_710(5),

  /// 7.1.2
  IA_CHANNEL_LAYOUT_712(6),

  /// 7.1.4
  IA_CHANNEL_LAYOUT_714(7),

  /// 3.1.2
  IA_CHANNEL_LAYOUT_312(8),

  /// binaural
  IA_CHANNEL_LAYOUT_BINAURAL(9),
  IA_CHANNEL_LAYOUT_COUNT(10),

  /// @brief The low-frequency effects subset (LFE) of 7.1.4ch
  IA_CHANNEL_LAYOUT_EXPANDED_LFE(16),

  /// @brief The surround subset (Ls/Rs) of 5.1.4ch
  IA_CHANNEL_LAYOUT_EXPANDED_STEREO_S(17),

  /// @brief The side surround subset (Lss/Rss) of 7.1.4ch
  IA_CHANNEL_LAYOUT_EXPANDED_STEREO_SS(18),

  /// @brief The rear surround subset (Lrs/Rrs) of 7.1.4ch
  IA_CHANNEL_LAYOUT_EXPANDED_STEREO_RS(19),

  /// @brief The top front subset (Ltf/Rtf) of 7.1.4ch
  IA_CHANNEL_LAYOUT_EXPANDED_STEREO_TF(20),

  /// @brief The top back subset (Ltb/Rtb) of 7.1.4ch
  IA_CHANNEL_LAYOUT_EXPANDED_STEREO_TB(21),

  /// @brief The top 4 channels (Ltf/Rtf/Ltb/Rtb) of 7.1.4ch
  IA_CHANNEL_LAYOUT_EXPANDED_TOP_4CH(22),

  /// @brief The front 3 channels (L/C/R) of 7.1.4ch
  IA_CHANNEL_LAYOUT_EXPANDED_3CH(23),

  /// @brief The subset of Loudspeaker configuration for Sound System H (9+10+3)
  /// of [ITU-2051-3]
  IA_CHANNEL_LAYOUT_EXPANDED_916(24),

  /// @brief The front subset (FL/FR) of 9.1.6ch
  IA_CHANNEL_LAYOUT_EXPANDED_STEREO_F(25),

  /// @brief The side subset (SiL/SiR) of 9.1.6ch
  IA_CHANNEL_LAYOUT_EXPANDED_STEREO_SI(26),

  /// @brief The top side subset (TpSiL/TpSiR) of 9.1.6ch
  IA_CHANNEL_LAYOUT_EXPANDED_STEREO_TPSI(27),

  /// @brief The top 6 channels (TpFL/TpFR/TpSiL/TpSiR/TpBL/TpBR) of 9.1.6ch
  IA_CHANNEL_LAYOUT_EXPANDED_TOP_6CH(28),

  /// @brief Loudspeaker configuration for Sound System H (9+10+3) of
  /// [ITU-2051-3]
  IA_CHANNEL_LAYOUT_EXPANDED_A293(29),

  /// @brief The low-frequency effects subset (LFE1/LFE2) of 10.2.9.3ch
  IA_CHANNEL_LAYOUT_EXPANDED_LFE_PAIR(30),

  /// @brief The bottom 3 channels (BtFL/BtFC/BtFR) of 10.2.9.3ch
  IA_CHANNEL_LAYOUT_EXPANDED_BOTTOM_3CH(31),

  /// @brief Loudspeaker configuration with the top and the bottom speakers
  /// added to Loudspeaker configuration for Sound System J (4+7+0) of
  /// [ITU-2051-3]
  IA_CHANNEL_LAYOUT_EXPANDED_7154(32),

  /// @brief The bottom 4 channels (BtFL/BtFR/BtBL/BtBR) of 7.1.5.4ch
  IA_CHANNEL_LAYOUT_EXPANDED_BOTTOM_4CH(33),

  /// @brief The top subset (TpC) of 7.1.5.4ch
  IA_CHANNEL_LAYOUT_EXPANDED_TOP_1CH(34),

  /// @brief The top 5 channels (Ltf/Rtf/TpC/Ltb/Rtb) of 7.1.5.4ch
  IA_CHANNEL_LAYOUT_EXPANDED_TOP_5CH(35),

  /// @brief The end of expanded loudspeaker layout
  IA_CHANNEL_LAYOUT_EXPANDED_END(36);

  static const IA_CHANNEL_LAYOUT_NONE = IA_CHANNEL_LAYOUT_INVALID;

  final int value;
  const IAMF_LoudspeakerLayoutType(this.value);

  static IAMF_LoudspeakerLayoutType fromValue(int value) => switch (value) {
    -1 => IA_CHANNEL_LAYOUT_INVALID,
    0 => IA_CHANNEL_LAYOUT_MONO,
    1 => IA_CHANNEL_LAYOUT_STEREO,
    2 => IA_CHANNEL_LAYOUT_510,
    3 => IA_CHANNEL_LAYOUT_512,
    4 => IA_CHANNEL_LAYOUT_514,
    5 => IA_CHANNEL_LAYOUT_710,
    6 => IA_CHANNEL_LAYOUT_712,
    7 => IA_CHANNEL_LAYOUT_714,
    8 => IA_CHANNEL_LAYOUT_312,
    9 => IA_CHANNEL_LAYOUT_BINAURAL,
    10 => IA_CHANNEL_LAYOUT_COUNT,
    16 => IA_CHANNEL_LAYOUT_EXPANDED_LFE,
    17 => IA_CHANNEL_LAYOUT_EXPANDED_STEREO_S,
    18 => IA_CHANNEL_LAYOUT_EXPANDED_STEREO_SS,
    19 => IA_CHANNEL_LAYOUT_EXPANDED_STEREO_RS,
    20 => IA_CHANNEL_LAYOUT_EXPANDED_STEREO_TF,
    21 => IA_CHANNEL_LAYOUT_EXPANDED_STEREO_TB,
    22 => IA_CHANNEL_LAYOUT_EXPANDED_TOP_4CH,
    23 => IA_CHANNEL_LAYOUT_EXPANDED_3CH,
    24 => IA_CHANNEL_LAYOUT_EXPANDED_916,
    25 => IA_CHANNEL_LAYOUT_EXPANDED_STEREO_F,
    26 => IA_CHANNEL_LAYOUT_EXPANDED_STEREO_SI,
    27 => IA_CHANNEL_LAYOUT_EXPANDED_STEREO_TPSI,
    28 => IA_CHANNEL_LAYOUT_EXPANDED_TOP_6CH,
    29 => IA_CHANNEL_LAYOUT_EXPANDED_A293,
    30 => IA_CHANNEL_LAYOUT_EXPANDED_LFE_PAIR,
    31 => IA_CHANNEL_LAYOUT_EXPANDED_BOTTOM_3CH,
    32 => IA_CHANNEL_LAYOUT_EXPANDED_7154,
    33 => IA_CHANNEL_LAYOUT_EXPANDED_BOTTOM_4CH,
    34 => IA_CHANNEL_LAYOUT_EXPANDED_TOP_1CH,
    35 => IA_CHANNEL_LAYOUT_EXPANDED_TOP_5CH,
    36 => IA_CHANNEL_LAYOUT_EXPANDED_END,
    _ => throw ArgumentError(
      'Unknown value for IAMF_LoudspeakerLayoutType: $value',
    ),
  };

  @override
  String toString() {
    if (this == IA_CHANNEL_LAYOUT_INVALID)
      return "IAMF_LoudspeakerLayoutType.IA_CHANNEL_LAYOUT_INVALID, IAMF_LoudspeakerLayoutType.IA_CHANNEL_LAYOUT_NONE";
    return super.toString();
  }
}

enum IAMF_SamplingRate {
  SAMPLING_RATE_NONE(0),
  SAMPLING_RATE_7350(7350),
  SAMPLING_RATE_8000(8000),
  SAMPLING_RATE_11025(11025),
  SAMPLING_RATE_16000(16000),
  SAMPLING_RATE_22050(22050),
  SAMPLING_RATE_24000(24000),
  SAMPLING_RATE_32000(32000),
  SAMPLING_RATE_44100(44100),
  SAMPLING_RATE_48000(48000),
  SAMPLING_RATE_64000(64000),
  SAMPLING_RATE_88200(88200),
  SAMPLING_RATE_96000(96000),
  SAMPLING_RATE_176400(176400),
  SAMPLING_RATE_192000(192000);

  final int value;
  const IAMF_SamplingRate(this.value);

  static IAMF_SamplingRate fromValue(int value) => switch (value) {
    0 => SAMPLING_RATE_NONE,
    7350 => SAMPLING_RATE_7350,
    8000 => SAMPLING_RATE_8000,
    11025 => SAMPLING_RATE_11025,
    16000 => SAMPLING_RATE_16000,
    22050 => SAMPLING_RATE_22050,
    24000 => SAMPLING_RATE_24000,
    32000 => SAMPLING_RATE_32000,
    44100 => SAMPLING_RATE_44100,
    48000 => SAMPLING_RATE_48000,
    64000 => SAMPLING_RATE_64000,
    88200 => SAMPLING_RATE_88200,
    96000 => SAMPLING_RATE_96000,
    176400 => SAMPLING_RATE_176400,
    192000 => SAMPLING_RATE_192000,
    _ => throw ArgumentError('Unknown value for IAMF_SamplingRate: $value'),
  };
}

enum IAMF_SampleBitDepth {
  SAMPLE_BIT_DEPTH_NONE(0),
  SAMPLE_BIT_DEPTH_16(16),
  SAMPLE_BIT_DEPTH_24(24),
  SAMPLE_BIT_DEPTH_32(32);

  final int value;
  const IAMF_SampleBitDepth(this.value);

  static IAMF_SampleBitDepth fromValue(int value) => switch (value) {
    0 => SAMPLE_BIT_DEPTH_NONE,
    16 => SAMPLE_BIT_DEPTH_16,
    24 => SAMPLE_BIT_DEPTH_24,
    32 => SAMPLE_BIT_DEPTH_32,
    _ => throw ArgumentError('Unknown value for IAMF_SampleBitDepth: $value'),
  };
}

enum IAMF_HeadphonesRenderingMode {
  HEADPHONES_RENDERING_MODE_WORLD_LOCKED_RESTRICTED(0),
  HEADPHONES_RENDERING_MODE_WORLD_LOCKED(1),
  HEADPHONES_RENDERING_MODE_HEAD_LOCKED(2),
  HEADPHONES_RENDERING_MODE_RESERVED(3);

  final int value;
  const IAMF_HeadphonesRenderingMode(this.value);

  static IAMF_HeadphonesRenderingMode fromValue(int value) => switch (value) {
    0 => HEADPHONES_RENDERING_MODE_WORLD_LOCKED_RESTRICTED,
    1 => HEADPHONES_RENDERING_MODE_WORLD_LOCKED,
    2 => HEADPHONES_RENDERING_MODE_HEAD_LOCKED,
    3 => HEADPHONES_RENDERING_MODE_RESERVED,
    _ => throw ArgumentError(
      'Unknown value for IAMF_HeadphonesRenderingMode: $value',
    ),
  };
}

enum IAMF_BinauralFilterProfile {
  BINAURAL_FILTER_PROFILE_AMBIENT(0),
  BINAURAL_FILTER_PROFILE_DIRECT(1),
  BINAURAL_FILTER_PROFILE_REVERBERANT(2),
  BINAURAL_FILTER_PROFILE_RESERVED(3);

  final int value;
  const IAMF_BinauralFilterProfile(this.value);

  static IAMF_BinauralFilterProfile fromValue(int value) => switch (value) {
    0 => BINAURAL_FILTER_PROFILE_AMBIENT,
    1 => BINAURAL_FILTER_PROFILE_DIRECT,
    2 => BINAURAL_FILTER_PROFILE_REVERBERANT,
    3 => BINAURAL_FILTER_PROFILE_RESERVED,
    _ => throw ArgumentError(
      'Unknown value for IAMF_BinauralFilterProfile: $value',
    ),
  };
}

/// @brief Audio element gain offset range information.
///
/// This structure defines the valid range for gain adjustment of a specific
/// audio element within a mix presentation. It allows users to adjust the
/// gain of individual audio elements within specified limits.
final class IamfElementGainOffsetRange extends ffi.Struct {
  /// < Minimum gain offset value in dB
  @ffi.Float()
  external double min;

  /// < Maximum gain offset value in dB
  @ffi.Float()
  external double max;
}

typedef iamf_element_gain_offset_range_t = IamfElementGainOffsetRange;

final class IamfElementPresentationInfo extends ffi.Struct {
  /// < Audio element identifier
  @ffi.Uint32()
  external int eid;

  /// < Headphones rendering mode
  @ffi.UnsignedInt()
  external int modeAsInt;

  IAMF_HeadphonesRenderingMode get mode =>
      IAMF_HeadphonesRenderingMode.fromValue(modeAsInt);

  /// < Binaural filter profile
  @ffi.UnsignedInt()
  external int profileAsInt;

  IAMF_BinauralFilterProfile get profile =>
      IAMF_BinauralFilterProfile.fromValue(profileAsInt);

  /// < Gain offset range
  external ffi.Pointer<iamf_element_gain_offset_range_t> gain_offset_range;
}

typedef iamf_element_presentation_info_t = IamfElementPresentationInfo;

/// @brief Mix presentation information structure.
///
/// This structure contains comprehensive information about a specific mix
/// presentation within an IAMF stream. Mix presentations define how different
/// audio elements are combined, processed, and presented to the listener,
/// supporting various output configurations including stereo, multichannel, and
/// binaural rendering.
///
/// Each mix presentation can contain multiple audio elements with different
/// rendering modes, gain adjustments, and spatial audio processing parameters.
/// This structure provides the metadata needed for applications to understand
/// and select appropriate mix presentations based on playback capabilities and
/// user preferences.
///
/// The structure includes information about audio elements such as their
/// identifiers, rendering modes (stereo, binaural), binaural filter profiles,
/// and gain offset ranges for user customization.
final class IamfMixPresentationInfo extends ffi.Struct {
  /// < Mix presentation identifier. Unique identifier for this mix
  /// presentation within the IAMF stream.
  @ffi.Uint32()
  external int id;

  /// < Number of audio elements in this mix
  /// presentation. Indicates the size of the
  /// elements array. */
  /// /**< Array of audio element presentation information. Contains detailed
  /// information about each audio element including rendering mode, binaural
  /// profile, and gain settings.
  @ffi.Uint32()
  external int num_audio_elements;

  external ffi.Pointer<iamf_element_presentation_info_t> elements;
}

typedef iamf_mix_presentation_info_t = IamfMixPresentationInfo;

/// @brief Audio element detailed information structure
///
/// This structure contains detailed information for each audio element,
/// including element type, codec ID, layout information and channel count.
final class IamfAudioElementInfo extends ffi.Struct {
  /// < Audio element ID
  @ffi.Uint32()
  external int element_id;

  /// < Codec ID
  @ffi.UnsignedInt()
  external int codec_idAsInt;

  IAMF_CodecID get codec_id => IAMF_CodecID.fromValue(codec_idAsInt);

  /// < Audio element type
  @ffi.Int()
  external int element_typeAsInt;

  IAMF_AudioElementType get element_type =>
      IAMF_AudioElementType.fromValue(element_typeAsInt);

  /// < Channel layout type
  @ffi.Int()
  external int channel_layoutAsInt;

  IAMF_LoudspeakerLayoutType get channel_layout =>
      IAMF_LoudspeakerLayoutType.fromValue(channel_layoutAsInt);

  /// < Number of channels
  @ffi.Uint32()
  external int num_channels;
}

typedef iamf_audio_element_info_t = IamfAudioElementInfo;

final class UnnamedStruct extends ffi.Struct {
  /// < Primary IAMF profile
  @ffi.Int()
  external int primary_profileAsInt;

  IA_Profile get primary_profile => IA_Profile.fromValue(primary_profileAsInt);

  /// < Additional IAMF profile
  @ffi.Int()
  external int additional_profileAsInt;

  IA_Profile get additional_profile =>
      IA_Profile.fromValue(additional_profileAsInt);

  /// < Output sampling rate */
  /// /**< Number of samples per channel per frame
  @ffi.UnsignedInt()
  external int sampling_rateAsInt;

  IAMF_SamplingRate get sampling_rate =>
      IAMF_SamplingRate.fromValue(sampling_rateAsInt);

  @ffi.Uint32()
  external int samples_per_channel_in_frame;

  @ffi.Uint32()
  external int audio_element_count;

  external ffi.Pointer<iamf_audio_element_info_t> audio_elements;

  @ffi.Uint32()
  external int mix_presentation_count;

  external ffi.Pointer<iamf_mix_presentation_info_t> mix_presentations;
}

/// @brief IAMF stream information structure.
///
/// This structure contains comprehensive information about an IAMF stream,
/// including codec configuration, audio parameters, and available mix
/// presentations. It is returned by @ref IAMF_decoder_get_stream_info and
/// provides details about the stream's capabilities and configuration.
final class IAMF_StreamInfo extends ffi.Struct {
  /// < Maximum frame size in samples
  @ffi.Uint32()
  external int max_frame_size;

  external UnnamedStruct iamf_stream_info;
}

typedef iamf_stream_info_t = IAMF_StreamInfo;

final class IAMF_Decoder extends ffi.Opaque {}

/// @}*/
/// /**\name Immersive audio decoder functions */
/// /**@{
typedef IAMF_DecoderHandle = ffi.Pointer<IAMF_Decoder>;

const int IAMF_OK = 0;

const int IAMF_ERR_BAD_ARG = -1;

const int IAMF_ERR_BUFFER_TOO_SMALL = -2;

const int IAMF_ERR_INTERNAL = -3;

const int IAMF_ERR_INVALID_PACKET = -4;

const int IAMF_ERR_INVALID_STATE = -5;

const int IAMF_ERR_UNIMPLEMENTED = -6;

const int IAMF_ERR_ALLOC_FAIL = -7;

const int IAMF_ERR_PENDING = -8;
